name: seera
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip=21.1.2
  - pip:
    - h5py==2.8.0
    - Cython>=0.29
    - Keras==2.2.4
    - matplotlib==3.0.1
    - tensorflow-gpu==1.11.0
    - gensim==3.8.3 #install it if you want to use lda model (gensim or mallet) in the topic modeling layer
    - networkx==2.5.1
    - nltk==3.6.2
    - numpy==1.19.5
    - pandas==1.1.5
    - scikit-learn==0.24.2
    - scikit-network
    - scipy==1.5.4
    - six==1.16.0
    - sklearn==0.0
    - tagme==0.1.3
    - seaborn==0.9.0
    - newspaper3k==0.2.8
    - pytrec-eval-terrier==0.5.2
    - ffmpeg==1.4
    - codecarbon==2.1.4
    - bitermplus==0.6.10 #install it if you want to use btm model in the topic modeling layer
    - line-profiler==4.0.0
    - torch==1.10.2
    - torchmetrics==0.8.2
    - params==0.9.0
#gsdmm==0.1 #install it if you want to use gsdmm model in the topic modeling layer, from github repo at https://github.com/rwalk/gsdmm.git