channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.1.2
  - pip:
    - h5py==2.8.0
    - Cython>=0.29
    - Keras==2.2.4
    - matplotlib==3.0.1
    - tensorflow-gpu==1.11.0
    - gensim==3.8.3
    - networkx==2.5.1
    - nltk==3.6.2
    - numpy==1.19.5
    - pandas==1.1.5
    - scikit-learn==0.24.2
    - scikit-network
    - scipy==1.5.4
    - six==1.16.0
    - sklearn==0.0
    - tagme==0.1.3
    - seaborn==0.9.0
    - newspaper3k==0.2.8